name: Build and test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout, install python and dependencies
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'pipenv'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          make install-all-deps

      # Lint and format checking
      - name: Lint sources
        run: make lint
      - name: Format sources # do not fix format issues
        run: make format-check

      # Update .env files
      - name: Generate default .env
        run: make dotenv-default
      - name: Generate integration .env
        run: make dotenv-inte
      - name: Commit .env files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update .env files
          file_pattern: '.env.*'

      # Integration and unit tests
      - name: Run unit tests
        run: make test-unit
      - name: Run integration tests
        # ".env" file required at root folder to run integration tests, rename ".env.inte" into ".env"
        run: |
          mv .env.inte .env
          make test-inte

      # Update openapi.json
      - name: Generate openapi.json
        run: make generate-openapi-json
      - name: Commit openapi.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update openapi.json
          file_pattern: 'openapi.json'
