name: Update .env files

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          make install-all-deps
      - name: Generate default .env
        run: make dotenv-default
      - name: Generate integration .env
        run: make dotenv-inte
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update .env files
          file_pattern: '.env.*'
